title: Trying to learn something new 
theme: minima
author: Eli Haskell
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is just for me to test and see how 
  this all works and to hopefully learn 
  something new on this website.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
